# Generated by Django 4.0.3 on 2024-04-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedrace',
            name='record',
        ),
    ]
