# Generated by Django 4.0.3 on 2024-04-03 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='description',
            field=models.TextField(default='', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='location_city',
            field=models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('gangwon', '강원'), ('chungcheong', '충청'), ('jeolla', '전라'), ('gyeongsang', '경상'), ('jeju', '제주'), ('etc', '기타')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='location_district',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='meet_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금'), ('sat', '토'), ('sun', '일')], default='', max_length=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='meet_time',
            field=models.CharField(choices=[('00:00 AM', '12:00 AM'), ('00:30 AM', '12:30 AM'), ('01:00 AM', '01:00 AM'), ('01:30 AM', '01:30 AM'), ('02:00 AM', '02:00 AM'), ('02:30 AM', '02:30 AM'), ('03:00 AM', '03:00 AM'), ('03:30 AM', '03:30 AM'), ('04:00 AM', '04:00 AM'), ('04:30 AM', '04:30 AM'), ('05:00 AM', '05:00 AM'), ('05:30 AM', '05:30 AM'), ('06:00 AM', '06:00 AM'), ('06:30 AM', '06:30 AM'), ('07:00 AM', '07:00 AM'), ('07:30 AM', '07:30 AM'), ('08:00 AM', '08:00 AM'), ('08:30 AM', '08:30 AM'), ('09:00 AM', '09:00 AM'), ('09:30 AM', '09:30 AM'), ('10:00 AM', '10:00 AM'), ('10:30 AM', '10:30 AM'), ('11:00 AM', '11:00 AM'), ('11:30 AM', '11:30 AM'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('13:00 PM', '01:00 PM'), ('13:30 PM', '01:30 PM'), ('14:00 PM', '02:00 PM'), ('14:30 PM', '02:30 PM'), ('15:00 PM', '03:00 PM'), ('15:30 PM', '03:30 PM'), ('16:00 PM', '04:00 PM'), ('16:30 PM', '04:30 PM'), ('17:00 PM', '05:00 PM'), ('17:30 PM', '05:30 PM'), ('18:00 PM', '06:00 PM'), ('18:30 PM', '06:30 PM'), ('19:00 PM', '07:00 PM'), ('19:30 PM', '07:30 PM'), ('20:00 PM', '08:00 PM'), ('20:30 PM', '08:30 PM'), ('21:00 PM', '09:00 PM'), ('21:30 PM', '09:30 PM'), ('22:00 PM', '10:00 PM'), ('22:30 PM', '10:30 PM'), ('23:00 PM', '11:00 PM'), ('23:30 PM', '11:30 PM')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='sns_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='crews/thumbnail/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='CrewReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crews.crew')),
            ],
        ),
        migrations.CreateModel(
            name='CrewFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crews.crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_crews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
