# Generated by Django 4.0.3 on 2024-04-04 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crews', '0002_crew_description_crew_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owned_crews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crewreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewd_crews', to=settings.AUTH_USER_MODEL),
        ),
    ]
